Reorder error evaluation when creating snapshot
Otherwise instead of reporting the actual I/O error the following error
message will be shown:

 Error: creating workspace snapshot: walking workspace: context canceled